### PR TITLE
Fix secret filters

### LINKED ISSUE #49: [Bug]: Unable to search secrets by name or assigned device (UI  and API)
### NetBox Secrets plugin version

v1.7.6

### NetBox version

v3.4.8

### Steps to Reproduce

1. add some secrets
2. try to search for a secret by attribute name with `/plugins/netbox_secrets/secrets/?name=My+Secret` (or `/api/`...)
3. try to search for a secret by attribute device with `/plugins/netbox_secrets/secrets/?device=my-server.com` (or `/api/`...)

### Expected Behavior

only secrets matching `name` or `device`, respecively, **exactly** should be returned. this worked in DanSheps' netbox\_secretstore plugin

### Observed Behavior

for name:
- UI: the parameter is ignored and all secrets are returned
- API: `HTTP/1.1 400 Bad Request` => `{"name":["“My Secret” is not a valid value."]}`

for device:
- UI: the parameter is ignored and all secrets are returned
- API: the parameter is ignored and all secrets are returned

This makes it impossible to retrieve secrets precisely, for example in automation. interestingly, querying by `?role=` works correctly in both old and new plugins.

### PR DESCRIPTION
**Pull request by kprince28**
# Pull Request

# Description

- Added filter for a name on API and UI
- Perform a quick search by assigned object name

## Close
#49

### CODE REVIEW

**Comment by uedvt359** [comment]
searching by name now works as expected from the API. In the UI there is now a "Name" drop-down, but that filters by ID. I can select e.g. "Secret" or "admin", but that only returns 1 result and the URL shows that it filtered by ID. It does not list all secrets named "Secret" or "admin".

image

Also, it looks like it is still not possible to search by `?device=` or `?virtual_machine=`.

**Comment by kprince28** [comment]
There it will return only one object when you are selecting one object through the form, and if you want to filter the secrets with the same name then you can even do a quick search on the UI.

In this plugin we provide a feature for defining more apps in the plugin's setting that you will need on the secrets and writing filtersets for them separately will be not a good idea.

**Review by abhi1693 — CHANGES_REQUESTED** [review]
`_object_repr` should not be directly exposed on the API for filtering. We should rather let people use `q` for filtering. If anyone wants specific objects, they can use the filter via content type and object ID which provides much deterministic results

**Comment by uedvt359** [comment]
Why not provide `device` and `virtual_machine` filters, like the old one?

**Comment by abhi1693** [comment]
@uedvt359 Because this plugin also supports netbox objects other than device and virtual machine. If you have a proposal to implement such filters, kindly open a new issue with more details.

**Review by abhi1693 — APPROVED** [review]

**Pull request merged**
